#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qtwebengine
Version  : 5.10.0.clean
Release  : 4
URL      : https://src.fedoraproject.org/repo/pkgs/rpms/qt5-qtwebengine/qtwebengine-everywhere-src-5.10.0-clean.tar.xz/sha512/d89fa0898176749b30a13dd50b58ca5c65a2a3ab67f210a567d791374cb95d206eff6aa6d41fa444dd9b88e4bf7f0544ed58486875b4c66d1d3974a2a7675c46/qtwebengine-everywhere-src-5.10.0-clean.tar.xz
Source0  : https://src.fedoraproject.org/repo/pkgs/rpms/qt5-qtwebengine/qtwebengine-everywhere-src-5.10.0-clean.tar.xz/sha512/d89fa0898176749b30a13dd50b58ca5c65a2a3ab67f210a567d791374cb95d206eff6aa6d41fa444dd9b88e4bf7f0544ed58486875b4c66d1d3974a2a7675c46/qtwebengine-everywhere-src-5.10.0-clean.tar.xz
Summary  : Ninja is a small build system with a focus on speed.
Group    : Development/Tools
License  : AFL-2.0 APSL-2.0 Apache-2.0 BSD-2-Clause BSD-3-Clause BSD-3-Clause-Clear BSL-1.0 FTL GFDL-1.2 GPL-2.0 GPL-3.0 HPND ICU IJG ISC LGPL-2.0 LGPL-2.1 LGPL-3.0 Libpng MIT MPL-1.1 MPL-2.0-no-copyleft-exception NCSA NTP OpenSSL SGI-B-2.0 Unlicense Zlib bzip2-1.0.6
Requires: qtwebengine-bin
Requires: qtwebengine-lib
Requires: qtwebengine-data
Requires: Sphinx
Requires: dnspython
Requires: nose
Requires: pyOpenSSL
Requires: pylint
Requires: python-mock
Requires: setuptools
Requires: six
Requires: tox
BuildRequires : alsa-lib-dev
BuildRequires : bison
BuildRequires : cmake
BuildRequires : dnspython
BuildRequires : flex
BuildRequires : go
BuildRequires : gperf
BuildRequires : grep
BuildRequires : icu4c-dev
BuildRequires : libjpeg-turbo-dev
BuildRequires : libvpx-dev
BuildRequires : libwebp-dev
BuildRequires : ninja
BuildRequires : pbr
BuildRequires : pip
BuildRequires : pkgconfig(Qt5Core)
BuildRequires : pkgconfig(Qt5Designer)
BuildRequires : pkgconfig(Qt5Gui)
BuildRequires : pkgconfig(Qt5Location)
BuildRequires : pkgconfig(Qt5Network)
BuildRequires : pkgconfig(Qt5PrintSupport)
BuildRequires : pkgconfig(Qt5Qml)
BuildRequires : pkgconfig(Qt5Quick)
BuildRequires : pkgconfig(Qt5QuickControls2)
BuildRequires : pkgconfig(Qt5QuickTest)
BuildRequires : pkgconfig(Qt5QuickWidgets)
BuildRequires : pkgconfig(Qt5Test)
BuildRequires : pkgconfig(Qt5WebChannel)
BuildRequires : pkgconfig(Qt5Widgets)
BuildRequires : pkgconfig(cairo)
BuildRequires : pkgconfig(cunit)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(dri2proto)
BuildRequires : pkgconfig(expat)
BuildRequires : pkgconfig(fontconfig)
BuildRequires : pkgconfig(freetype2)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(glproto)
BuildRequires : pkgconfig(harfbuzz)
BuildRequires : pkgconfig(icu-i18n)
BuildRequires : pkgconfig(jsoncpp)
BuildRequires : pkgconfig(lcms2)
BuildRequires : pkgconfig(libdrm)
BuildRequires : pkgconfig(libdrm_intel)
BuildRequires : pkgconfig(libdrm_nouveau)
BuildRequires : pkgconfig(libdrm_radeon)
BuildRequires : pkgconfig(libevent)
BuildRequires : pkgconfig(libffi)
BuildRequires : pkgconfig(libkms)
BuildRequires : pkgconfig(liblzma)
BuildRequires : pkgconfig(libpng)
BuildRequires : pkgconfig(libpulse)
BuildRequires : pkgconfig(libpulse-mainloop-glib)
BuildRequires : pkgconfig(libudev)
BuildRequires : pkgconfig(libva)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(libxslt)
BuildRequires : pkgconfig(nss)
BuildRequires : pkgconfig(opus)
BuildRequires : pkgconfig(pciaccess)
BuildRequires : pkgconfig(protobuf)
BuildRequires : pkgconfig(pthread-stubs)
BuildRequires : pkgconfig(valgrind)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(wayland-server)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(x11-xcb)
BuildRequires : pkgconfig(xcb)
BuildRequires : pkgconfig(xcb-dri2)
BuildRequires : pkgconfig(xcb-xfixes)
BuildRequires : pkgconfig(xcomposite)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xorg-server)
BuildRequires : pkgconfig(xrandr)
BuildRequires : pkgconfig(xtst)
BuildRequires : pkgconfig(xvmc)
BuildRequires : pkgconfig(xxf86vm)
BuildRequires : pkgconfig(zlib)
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : qtbase-dev
BuildRequires : qttools-dev
BuildRequires : scons
BuildRequires : sed
BuildRequires : setuptools
BuildRequires : six
BuildRequires : snappy-dev

%description
Ninja is yet another build system. It takes as input the interdependencies of files (typically source code and output executables) and
orchestrates building them, quickly.

Ninja joins a sea of other build systems. Its distinguishing goal is to be fast. It is born from my work on the Chromium browser project,
which has over 30,000 source files and whose other build systems (including one built from custom non-recursive Makefiles) can take ten
seconds to start building after changing one file. Ninja is under a second.

%package bin
Summary: bin components for the qtwebengine package.
Group: Binaries
Requires: qtwebengine-data

%description bin
bin components for the qtwebengine package.


%package data
Summary: data components for the qtwebengine package.
Group: Data

%description data
data components for the qtwebengine package.


%package dev
Summary: dev components for the qtwebengine package.
Group: Development
Requires: qtwebengine-lib
Requires: qtwebengine-bin
Requires: qtwebengine-data
Provides: qtwebengine-devel

%description dev
dev components for the qtwebengine package.


%package lib
Summary: lib components for the qtwebengine package.
Group: Libraries
Requires: qtwebengine-data

%description lib
lib components for the qtwebengine package.


%prep
%setup -q -n qtwebengine-everywhere-src-5.10.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
`pkg-config --variable=host_bins Qt5Core $(sed -n '/MODULE_VERSION */s///p' .qmake.conf 2>/dev/null)`/qmake --
test -r config.log && cat config.log
make  %{?_smp_mflags}

%install
make INSTALL_ROOT=%{buildroot} install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qwebengine_convert_dict
/usr/libexec/QtWebEngineProcess

%files data
%defattr(-,root,root,-)
/usr/share/qt5/resources/icudtl.dat
/usr/share/qt5/resources/qtwebengine_devtools_resources.pak
/usr/share/qt5/resources/qtwebengine_resources.pak
/usr/share/qt5/resources/qtwebengine_resources_100p.pak
/usr/share/qt5/resources/qtwebengine_resources_200p.pak
/usr/share/qt5/translations/qtwebengine_locales/am.pak
/usr/share/qt5/translations/qtwebengine_locales/ar.pak
/usr/share/qt5/translations/qtwebengine_locales/bg.pak
/usr/share/qt5/translations/qtwebengine_locales/bn.pak
/usr/share/qt5/translations/qtwebengine_locales/ca.pak
/usr/share/qt5/translations/qtwebengine_locales/cs.pak
/usr/share/qt5/translations/qtwebengine_locales/da.pak
/usr/share/qt5/translations/qtwebengine_locales/de.pak
/usr/share/qt5/translations/qtwebengine_locales/el.pak
/usr/share/qt5/translations/qtwebengine_locales/en-GB.pak
/usr/share/qt5/translations/qtwebengine_locales/en-US.pak
/usr/share/qt5/translations/qtwebengine_locales/es-419.pak
/usr/share/qt5/translations/qtwebengine_locales/es.pak
/usr/share/qt5/translations/qtwebengine_locales/et.pak
/usr/share/qt5/translations/qtwebengine_locales/fa.pak
/usr/share/qt5/translations/qtwebengine_locales/fi.pak
/usr/share/qt5/translations/qtwebengine_locales/fil.pak
/usr/share/qt5/translations/qtwebengine_locales/fr.pak
/usr/share/qt5/translations/qtwebengine_locales/gu.pak
/usr/share/qt5/translations/qtwebengine_locales/he.pak
/usr/share/qt5/translations/qtwebengine_locales/hi.pak
/usr/share/qt5/translations/qtwebengine_locales/hr.pak
/usr/share/qt5/translations/qtwebengine_locales/hu.pak
/usr/share/qt5/translations/qtwebengine_locales/id.pak
/usr/share/qt5/translations/qtwebengine_locales/it.pak
/usr/share/qt5/translations/qtwebengine_locales/ja.pak
/usr/share/qt5/translations/qtwebengine_locales/kn.pak
/usr/share/qt5/translations/qtwebengine_locales/ko.pak
/usr/share/qt5/translations/qtwebengine_locales/lt.pak
/usr/share/qt5/translations/qtwebengine_locales/lv.pak
/usr/share/qt5/translations/qtwebengine_locales/ml.pak
/usr/share/qt5/translations/qtwebengine_locales/mr.pak
/usr/share/qt5/translations/qtwebengine_locales/ms.pak
/usr/share/qt5/translations/qtwebengine_locales/nb.pak
/usr/share/qt5/translations/qtwebengine_locales/nl.pak
/usr/share/qt5/translations/qtwebengine_locales/pl.pak
/usr/share/qt5/translations/qtwebengine_locales/pt-BR.pak
/usr/share/qt5/translations/qtwebengine_locales/pt-PT.pak
/usr/share/qt5/translations/qtwebengine_locales/ro.pak
/usr/share/qt5/translations/qtwebengine_locales/ru.pak
/usr/share/qt5/translations/qtwebengine_locales/sk.pak
/usr/share/qt5/translations/qtwebengine_locales/sl.pak
/usr/share/qt5/translations/qtwebengine_locales/sr.pak
/usr/share/qt5/translations/qtwebengine_locales/sv.pak
/usr/share/qt5/translations/qtwebengine_locales/sw.pak
/usr/share/qt5/translations/qtwebengine_locales/ta.pak
/usr/share/qt5/translations/qtwebengine_locales/te.pak
/usr/share/qt5/translations/qtwebengine_locales/th.pak
/usr/share/qt5/translations/qtwebengine_locales/tr.pak
/usr/share/qt5/translations/qtwebengine_locales/uk.pak
/usr/share/qt5/translations/qtwebengine_locales/vi.pak
/usr/share/qt5/translations/qtwebengine_locales/zh-CN.pak
/usr/share/qt5/translations/qtwebengine_locales/zh-TW.pak

%files dev
%defattr(-,root,root,-)
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginecertificateerror_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginecontextmenurequest_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginedialogrequests_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginedownloaditem_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginedownloaditem_p_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginefaviconprovider_p_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginehistory_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginehistory_p_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebengineloadrequest_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginenavigationrequest_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginenewviewrequest_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebengineprofile_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginescript_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginesettings_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginesingleton_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebenginetestsupport_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebengineview_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qquickwebengineview_p_p.h
/usr/include/qt5/QtWebEngine/5.10.0/QtWebEngine/private/qtwebengineglobal_p.h
/usr/include/qt5/QtWebEngine/QQuickWebEngineProfile
/usr/include/qt5/QtWebEngine/QQuickWebEngineScript
/usr/include/qt5/QtWebEngine/QtWebEngine
/usr/include/qt5/QtWebEngine/QtWebEngineDepends
/usr/include/qt5/QtWebEngine/QtWebEngineVersion
/usr/include/qt5/QtWebEngine/qquickwebengineprofile.h
/usr/include/qt5/QtWebEngine/qquickwebenginescript.h
/usr/include/qt5/QtWebEngine/qtwebengineglobal.h
/usr/include/qt5/QtWebEngine/qtwebengineversion.h
/usr/include/qt5/QtWebEngineCore/5.10.0/QtWebEngineCore/private/qtwebenginecoreglobal_p.h
/usr/include/qt5/QtWebEngineCore/5.10.0/QtWebEngineCore/private/qwebenginecallback_p.h
/usr/include/qt5/QtWebEngineCore/5.10.0/QtWebEngineCore/private/qwebenginecookiestore_p.h
/usr/include/qt5/QtWebEngineCore/5.10.0/QtWebEngineCore/private/qwebengineurlrequestinfo_p.h
/usr/include/qt5/QtWebEngineCore/QWebEngineCallback
/usr/include/qt5/QtWebEngineCore/QWebEngineCookieStore
/usr/include/qt5/QtWebEngineCore/QWebEngineHttpRequest
/usr/include/qt5/QtWebEngineCore/QWebEngineUrlRequestInfo
/usr/include/qt5/QtWebEngineCore/QWebEngineUrlRequestInterceptor
/usr/include/qt5/QtWebEngineCore/QWebEngineUrlRequestJob
/usr/include/qt5/QtWebEngineCore/QWebEngineUrlSchemeHandler
/usr/include/qt5/QtWebEngineCore/QtWebEngineCore
/usr/include/qt5/QtWebEngineCore/QtWebEngineCoreDepends
/usr/include/qt5/QtWebEngineCore/QtWebEngineCoreVersion
/usr/include/qt5/QtWebEngineCore/qtwebenginecoreglobal.h
/usr/include/qt5/QtWebEngineCore/qtwebenginecoreversion.h
/usr/include/qt5/QtWebEngineCore/qwebenginecallback.h
/usr/include/qt5/QtWebEngineCore/qwebenginecookiestore.h
/usr/include/qt5/QtWebEngineCore/qwebenginehttprequest.h
/usr/include/qt5/QtWebEngineCore/qwebengineurlrequestinfo.h
/usr/include/qt5/QtWebEngineCore/qwebengineurlrequestinterceptor.h
/usr/include/qt5/QtWebEngineCore/qwebengineurlrequestjob.h
/usr/include/qt5/QtWebEngineCore/qwebengineurlschemehandler.h
/usr/include/qt5/QtWebEngineWidgets/5.10.0/QtWebEngineWidgets/private/qwebenginedownloaditem_p.h
/usr/include/qt5/QtWebEngineWidgets/5.10.0/QtWebEngineWidgets/private/qwebenginehistory_p.h
/usr/include/qt5/QtWebEngineWidgets/5.10.0/QtWebEngineWidgets/private/qwebenginepage_p.h
/usr/include/qt5/QtWebEngineWidgets/5.10.0/QtWebEngineWidgets/private/qwebengineprofile_p.h
/usr/include/qt5/QtWebEngineWidgets/5.10.0/QtWebEngineWidgets/private/qwebenginescriptcollection_p.h
/usr/include/qt5/QtWebEngineWidgets/5.10.0/QtWebEngineWidgets/private/qwebengineview_p.h
/usr/include/qt5/QtWebEngineWidgets/QWebEngineCertificateError
/usr/include/qt5/QtWebEngineWidgets/QWebEngineContextMenuData
/usr/include/qt5/QtWebEngineWidgets/QWebEngineDownloadItem
/usr/include/qt5/QtWebEngineWidgets/QWebEngineFullScreenRequest
/usr/include/qt5/QtWebEngineWidgets/QWebEngineHistory
/usr/include/qt5/QtWebEngineWidgets/QWebEngineHistoryItem
/usr/include/qt5/QtWebEngineWidgets/QWebEnginePage
/usr/include/qt5/QtWebEngineWidgets/QWebEngineProfile
/usr/include/qt5/QtWebEngineWidgets/QWebEngineScript
/usr/include/qt5/QtWebEngineWidgets/QWebEngineScriptCollection
/usr/include/qt5/QtWebEngineWidgets/QWebEngineSettings
/usr/include/qt5/QtWebEngineWidgets/QWebEngineView
/usr/include/qt5/QtWebEngineWidgets/QtWebEngineWidgets
/usr/include/qt5/QtWebEngineWidgets/QtWebEngineWidgetsDepends
/usr/include/qt5/QtWebEngineWidgets/QtWebEngineWidgetsVersion
/usr/include/qt5/QtWebEngineWidgets/qtwebenginewidgetsglobal.h
/usr/include/qt5/QtWebEngineWidgets/qtwebenginewidgetsversion.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginecertificateerror.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginecontextmenudata.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginedownloaditem.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginefullscreenrequest.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginehistory.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginepage.h
/usr/include/qt5/QtWebEngineWidgets/qwebengineprofile.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginescript.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginescriptcollection.h
/usr/include/qt5/QtWebEngineWidgets/qwebenginesettings.h
/usr/include/qt5/QtWebEngineWidgets/qwebengineview.h
/usr/lib64/cmake/Qt5Designer/Qt5Designer_QWebEngineViewPlugin.cmake
/usr/lib64/cmake/Qt5WebEngine/Qt5WebEngineConfig.cmake
/usr/lib64/cmake/Qt5WebEngine/Qt5WebEngineConfigVersion.cmake
/usr/lib64/cmake/Qt5WebEngineCore/Qt5WebEngineCoreConfig.cmake
/usr/lib64/cmake/Qt5WebEngineCore/Qt5WebEngineCoreConfigVersion.cmake
/usr/lib64/cmake/Qt5WebEngineWidgets/Qt5WebEngineWidgetsConfig.cmake
/usr/lib64/cmake/Qt5WebEngineWidgets/Qt5WebEngineWidgetsConfigVersion.cmake
/usr/lib64/libQt5WebEngine.la
/usr/lib64/libQt5WebEngine.prl
/usr/lib64/libQt5WebEngine.so
/usr/lib64/libQt5WebEngineCore.la
/usr/lib64/libQt5WebEngineCore.prl
/usr/lib64/libQt5WebEngineCore.so
/usr/lib64/libQt5WebEngineWidgets.la
/usr/lib64/libQt5WebEngineWidgets.prl
/usr/lib64/libQt5WebEngineWidgets.so
/usr/lib64/pkgconfig/Qt5WebEngine.pc
/usr/lib64/pkgconfig/Qt5WebEngineCore.pc
/usr/lib64/pkgconfig/Qt5WebEngineWidgets.pc
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_webengine_private.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecore_private.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets.pri
/usr/lib64/qt5/mkspecs/modules/qt_lib_webenginewidgets_private.pri

%files lib
%defattr(-,root,root,-)
/usr/lib64/libQt5WebEngine.so.5
/usr/lib64/libQt5WebEngine.so.5.10
/usr/lib64/libQt5WebEngine.so.5.10.0
/usr/lib64/libQt5WebEngineCore.so.5
/usr/lib64/libQt5WebEngineCore.so.5.10
/usr/lib64/libQt5WebEngineCore.so.5.10.0
/usr/lib64/libQt5WebEngineWidgets.so.5
/usr/lib64/libQt5WebEngineWidgets.so.5.10
/usr/lib64/libQt5WebEngineWidgets.so.5.10.0
/usr/lib64/qt5/plugins/designer/libqwebengineview.so
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/AlertDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/AuthenticationDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/ColorDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/ConfirmDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/FilePicker.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/Menu.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/MenuItem.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/MenuSeparator.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/MessageBubble.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/PromptDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/ToolTip.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls1Delegates/qmldir
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/AlertDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/AuthenticationDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/ConfirmDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/Menu.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/MenuItem.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/MenuSeparator.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/PromptDialog.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/ToolTip.qml
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/information.png
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/qmldir
/usr/lib64/qt5/qml/QtWebEngine/Controls2Delegates/question.png
/usr/lib64/qt5/qml/QtWebEngine/libqtwebengineplugin.so
/usr/lib64/qt5/qml/QtWebEngine/plugins.qmltypes
/usr/lib64/qt5/qml/QtWebEngine/qmldir
